[phases.setup]
# força instalação do nodejs-18_x
packages = ["nodejs-18_x"]

[phases.build]
commands = [
  "cd backend",
  "npm install",
  "npm run build"
]

[phases.start]
commands = [
  "cd backend",
  "npm run start:prod"
]